export const ActionTypes = {
    GET_CURRENT_DATA_REQUEST: "GET_CURRENT_DATA_REQUEST",
    GET_CURRENT_DATA_FAILURE: "GET_CURRENT_DATA_FAILURE",
    GET_CURRENT_DATA_SUCCESS: "GET_CURRENT_DATA_SUCCESS",

    GET_OLD_DATA_REQUEST: "GET_OLD_DATA_REQUEST",
    GET_OLD_DATA_FAILURE: "GET_OLD_DATA_FAILURE",
    GET_OLD_DATA_SUCCESS: "GET_OLD_DATA_SUCCESS",
};
